/*
===========================================================================
Copyright (C) 2026 JKX contributors

This file is part of JKX.

JKX is free software; you can redistribute it and/or modify it under the terms
of the GNU General Public License version 2 as published by the Free Software
Foundation.
===========================================================================
*/

// One zip handle, two readers.
//
// A pack_t keeps a single unzFile open for the whole archive and hands it to
// any caller that did not ask for its own - which is nearly all of them, since
// uniqueFILE defaults to false everywhere except the music streamer and the
// cinematic player. That is an optimisation with a condition attached, and the
// condition was never written down: a zip handle carries one position and one
// inflate state, so it can serve one reader at a time.
//
// FS_FOpenFileRead moves the shared handle to the file it was asked for
// (unzSetOffset) and starts a fresh stream there (unzOpenCurrentFile). If
// another file from the same pack is already open on that handle, its reader is
// still holding a valid fileHandle_t, still calling FS_Read, and now getting
// bytes from somewhere else entirely. Nothing returns an error anywhere.
//
// This test is about the mechanism rather than about the filesystem: it builds
// an archive, reads two entries out of it the way the engine does, and asks
// what comes back. Two arrangements:
//
//   1. one handle for both entries - what the engine used to do. The claim is
//      that the first reader's bytes are wrong, and it is worth stating as a
//      test rather than as a comment because it is the whole reason for the
//      change;
//   2. one handle each - what the engine does now when the shared one is busy.
//      Both streams have to come back byte for byte.
//
// The archive is written here rather than committed, because a fixture that is
// generated by one program and read by another drifts, and this one is small
// enough to be obvious: two entries, one deflated, one stored, each filled with
// a pattern that says which file and which offset every byte came from.

#include "minizip/unzip.h"

#include <zlib.h>

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <vector>

// minizip in this tree is built against the engine's zone allocator. A test is
// not the engine, so these stand in for it - see third_party/minizip/unzip.c.
extern "C" void *openjk_minizip_malloc( int size );
extern "C" void openjk_minizip_free( void *p );

extern "C" void *openjk_minizip_malloc( int size )
{
	return malloc( (size_t)size );
}

extern "C" void openjk_minizip_free( void *p )
{
	free( p );
}


namespace
{

int g_failures = 0;
int g_checks = 0;

void check( bool condition, const char *what )
{
	g_checks++;
	if ( !condition ) {
		g_failures++;
		printf( "FAIL: %s\n", what );
	}
}


// A pattern that identifies both the file and the position. Repeating bytes
// would let a wrong read look right by accident, which is exactly the failure
// this is trying to see.
std::vector<unsigned char> pattern( unsigned char tag, size_t len )
{
	std::vector<unsigned char> v( len );

	for ( size_t i = 0; i < len; i++ ) {
		v[i] = (unsigned char)( tag ^ ( i * 31 + ( i >> 8 ) * 7 ) );
	}
	return v;
}


void put16( std::vector<unsigned char> &out, unsigned int v )
{
	out.push_back( (unsigned char)( v & 0xff ) );
	out.push_back( (unsigned char)( ( v >> 8 ) & 0xff ) );
}

void put32( std::vector<unsigned char> &out, unsigned long v )
{
	for ( int i = 0; i < 4; i++ ) {
		out.push_back( (unsigned char)( ( v >> ( 8 * i ) ) & 0xff ) );
	}
}


// Raw deflate, which is what a zip entry holds - not a zlib stream, so no
// two-byte header and no adler at the end. That is the -MAX_WBITS below.
bool deflateRaw( const std::vector<unsigned char> &in, std::vector<unsigned char> &out )
{
	z_stream s;

	memset( &s, 0, sizeof( s ) );
	if ( deflateInit2( &s, Z_BEST_COMPRESSION, Z_DEFLATED, -MAX_WBITS, 8,
			Z_DEFAULT_STRATEGY ) != Z_OK ) {
		return false;
	}

	out.assign( in.size() + in.size() / 2 + 128, 0 );
	s.next_in = const_cast<Bytef *>( in.data() );
	s.avail_in = (uInt)in.size();
	s.next_out = out.data();
	s.avail_out = (uInt)out.size();

	const int rc = deflate( &s, Z_FINISH );

	out.resize( out.size() - s.avail_out );
	deflateEnd( &s );
	return rc == Z_STREAM_END;
}


struct Entry
{
	std::string					name;
	std::vector<unsigned char>	plain;
	bool						deflated;
};


// The smallest zip that minizip will read: local header and data per entry,
// then a central directory, then the end record. No zip64, no data descriptors,
// no extra fields - none of which the engine's archives use either.
bool writeZip( const char *path, const std::vector<Entry> &entries )
{
	std::vector<unsigned char>	file;
	std::vector<unsigned long>	offsets;
	std::vector<unsigned long>	sizes;

	for ( size_t i = 0; i < entries.size(); i++ ) {
		const Entry					&e = entries[i];
		std::vector<unsigned char>	body;

		if ( e.deflated ) {
			if ( !deflateRaw( e.plain, body ) ) {
				return false;
			}
		} else {
			body = e.plain;
		}

		offsets.push_back( (unsigned long)file.size() );
		sizes.push_back( (unsigned long)body.size() );

		const unsigned long crc =
			crc32( crc32( 0L, Z_NULL, 0 ), e.plain.data(), (uInt)e.plain.size() );

		put32( file, 0x04034b50 );
		put16( file, 20 );					// version needed
		put16( file, 0 );					// flags
		put16( file, e.deflated ? 8 : 0 );	// method
		put16( file, 0 );					// time
		put16( file, 0 );					// date
		put32( file, crc );
		put32( file, (unsigned long)body.size() );
		put32( file, (unsigned long)e.plain.size() );
		put16( file, (unsigned int)e.name.size() );
		put16( file, 0 );					// extra length
		file.insert( file.end(), e.name.begin(), e.name.end() );
		file.insert( file.end(), body.begin(), body.end() );
	}

	const unsigned long cdOffset = (unsigned long)file.size();

	for ( size_t i = 0; i < entries.size(); i++ ) {
		const Entry			&e = entries[i];
		const unsigned long	crc =
			crc32( crc32( 0L, Z_NULL, 0 ), e.plain.data(), (uInt)e.plain.size() );

		put32( file, 0x02014b50 );
		put16( file, 20 );					// version made by
		put16( file, 20 );					// version needed
		put16( file, 0 );					// flags
		put16( file, e.deflated ? 8 : 0 );	// method
		put16( file, 0 );					// time
		put16( file, 0 );					// date
		put32( file, crc );
		put32( file, sizes[i] );
		put32( file, (unsigned long)e.plain.size() );
		put16( file, (unsigned int)e.name.size() );
		put16( file, 0 );					// extra
		put16( file, 0 );					// comment
		put16( file, 0 );					// disk number
		put16( file, 0 );					// internal attributes
		put32( file, 0 );					// external attributes
		put32( file, offsets[i] );
		file.insert( file.end(), e.name.begin(), e.name.end() );
	}

	const unsigned long cdSize = (unsigned long)file.size() - cdOffset;

	put32( file, 0x06054b50 );
	put16( file, 0 );
	put16( file, 0 );
	put16( file, (unsigned int)entries.size() );
	put16( file, (unsigned int)entries.size() );
	put32( file, cdSize );
	put32( file, cdOffset );
	put16( file, 0 );

	FILE *f = fopen( path, "wb" );

	if ( !f ) {
		return false;
	}
	const bool ok = fwrite( file.data(), 1, file.size(), f ) == file.size();
	fclose( f );
	return ok;
}


// What FS_FOpenFileRead records for a file it found in a pack: where the entry
// sits, so that opening it again is a seek rather than a search.
unsigned long offsetOf( unzFile z, const char *name )
{
	if ( unzLocateFile( z, name, 2 ) != UNZ_OK ) {
		return 0;
	}
	return unzGetOffset( z );
}


// FS_FOpenFileRead's pak branch, in the two lines that matter.
void openAt( unzFile z, unsigned long pos )
{
	unzSetOffset( z, pos );
	unzOpenCurrentFile( z );
}


void testOneHandleForBoth( const char *path,
	const std::vector<unsigned char> &a, const std::vector<unsigned char> &b )
{
	unzFile	z = unzOpen( path );

	check( z != NULL, "the archive opens" );
	if ( !z ) {
		return;
	}

	const unsigned long	posA = offsetOf( z, "a.dat" );
	const unsigned long	posB = offsetOf( z, "b.dat" );
	const int			half = (int)( a.size() / 2 );

	std::vector<unsigned char>	firstHalf( half, 0 );
	std::vector<unsigned char>	secondHalf( half, 0 );
	std::vector<unsigned char>	fromB( b.size() / 2, 0 );

	// Reader one opens a.dat and reads half of it.
	openAt( z, posA );
	check( unzReadCurrentFile( z, firstHalf.data(), half ) == half,
		"the first reader gets the bytes it asked for" );
	check( memcmp( firstHalf.data(), a.data(), half ) == 0,
		"and they are the first file's bytes, while it is the only reader" );

	// Reader two opens b.dat on the same handle - which is what the engine did
	// for any two files from one pack.
	openAt( z, posB );
	unzReadCurrentFile( z, fromB.data(), (unsigned)fromB.size() );

	// Reader one is still holding its handle and reads on.
	const int got = unzReadCurrentFile( z, secondHalf.data(), half );

	// This is the defect, stated as a claim rather than left as a comment: what
	// comes back is not the rest of a.dat. It may be short, it may be b.dat, it
	// may be an error - the one thing it is not is right, and nothing told the
	// caller.
	const bool correct = ( got == half )
		&& memcmp( secondHalf.data(), a.data() + half, half ) == 0;

	check( !correct,
		"a second file opened on the same handle takes the first one's place" );
	printf( "  one handle for both: the first reader's second read returned %i "
		"byte(s) of %i, %s\n",
		got, half, correct ? "and they were right" : "and they were not its own" );

	unzCloseCurrentFile( z );
	unzClose( z );
}


void testOneHandleEach( const char *path,
	const std::vector<unsigned char> &a, const std::vector<unsigned char> &b )
{
	unzFile	za = unzOpen( path );
	unzFile	zb = unzOpen( path );

	check( za != NULL && zb != NULL, "two handles on one archive both open" );
	if ( !za || !zb ) {
		return;
	}

	const unsigned long	posA = offsetOf( za, "a.dat" );
	const unsigned long	posB = offsetOf( zb, "b.dat" );

	openAt( za, posA );
	openAt( zb, posB );

	// Interleaved in small pieces, because a defect that only shows up when the
	// two streams are actually alternating would not show up in one pass each.
	std::vector<unsigned char>	gotA( a.size(), 0 );
	std::vector<unsigned char>	gotB( b.size(), 0 );
	size_t						atA = 0, atB = 0;
	const size_t				step = 37;
	bool						shortRead = false;

	while ( atA < a.size() || atB < b.size() ) {
		if ( atA < a.size() ) {
			const size_t want = ( a.size() - atA < step ) ? a.size() - atA : step;
			const int got = unzReadCurrentFile( za, gotA.data() + atA, (unsigned)want );

			if ( got != (int)want ) {
				shortRead = true;
				break;
			}
			atA += want;
		}
		if ( atB < b.size() ) {
			const size_t want = ( b.size() - atB < step ) ? b.size() - atB : step;
			const int got = unzReadCurrentFile( zb, gotB.data() + atB, (unsigned)want );

			if ( got != (int)want ) {
				shortRead = true;
				break;
			}
			atB += want;
		}
	}

	check( !shortRead, "neither stream runs short when they have a handle each" );
	check( gotA == a, "the deflated entry reads back exactly" );
	check( gotB == b, "the stored entry reads back exactly" );

	unzCloseCurrentFile( za );
	unzCloseCurrentFile( zb );
	unzClose( za );
	unzClose( zb );
}

}	// namespace


int main( int argc, char **argv )
{
	const char					*path = ( argc > 1 ) ? argv[1] : "pk3_share_test.pk3";
	std::vector<Entry>			entries;
	std::vector<unsigned char>	a = pattern( 0xa5, 40000 );
	std::vector<unsigned char>	b = pattern( 0x5a, 40000 );

	// One deflated and one stored, because a zip may hold either and minizip
	// takes a different path through each - a fixture that is all one method
	// tests half of what it looks like it tests.
	entries.push_back( Entry{ "a.dat", a, true } );
	entries.push_back( Entry{ "b.dat", b, false } );

	if ( !writeZip( path, entries ) ) {
		printf( "FAIL: could not write the test archive at %s\n", path );
		return 1;
	}

	testOneHandleForBoth( path, a, b );
	testOneHandleEach( path, a, b );

	remove( path );

	printf( "pk3 shared handle: %i check(s), %i failure(s)\n", g_checks, g_failures );
	return g_failures ? 1 : 0;
}
