#!/usr/bin/env python3
"""Write ext_data/items.dat and ext_data/weapons.dat for the smoke fixture.

Both files are MANDATORY and neither has a compiled-in fallback. items.dat in
particular: bg_itemlist is declared empty and filled entirely from that file, so
without it every item has no classname, and G_InitGame stops at "Couldn't find
item for inventory 0" before the first frame. The engine ships no copy - the
retail assets do - which is why a fixture that owns no retail data has to write
its own.

WHY THIS IS GENERATED AND NOT CHECKED IN. The hand-written pair it replaces
covered exactly the weapons the fixture map needed and stopped at WP_TURRET. The
fixture map loaded, every lane was green, and the first real retail map died on

    ERROR: Couldn't find item for weapon 27

which is WP_SCEPTER: one of seven weapons past the end of the list. Nothing was
wrong with the engine. The table simply described a smaller game than the one it
was in, and no fixture could see that because every fixture used the same table.

So the list is read out of the sources it has to agree with - the WP_ enum in
games/<game>/game/weapons.h and the names g_itemLoad.cpp accepts - and a weapon
added to either one appears here without anyone remembering to add it. The two
games have different enums, which is the other half of the reason: one shared
file cannot be right for both, and a name the other game does not know is worse
than useless. JK2's parser answers an unrecognised itemname with slot 0 and then
writes the block's type and tag into it, so an unknown entry does not get
ignored - it turns the null item into a weapon.

Usage:
    make_item_tables.py --game ja --out RUNDIR/base/ext_data [--repo PATH]
"""

import argparse
import os
import re
import sys

# WP_FOO -> ITM_FOO_PICKUP covers most of them. These are the ones where the
# item is not named after the weapon, taken from the retail tables.
NAME_EXCEPTIONS = {
    "WP_THERMAL": "ITM_THERMAL_DET_PICKUP",
    "WP_MELEE": "ITM_MELEE",
    "WP_CONCUSSION": "ITM_CONCUSSION_RIFLE_PICKUP",
}

# The holdables, which are not weapons and are not in the WP_ enum. G_InitGame
# walks every bit of the player's starting inventory and asks
# FindItemForInventory for each, so a missing one is fatal in the same way a
# missing weapon is. Both games take the same seven.
HOLDABLES = [
    ("ITM_BINOCULARS_PICKUP", "item_electrobinoculars", "INV_ELECTROBINOCULARS"),
    ("ITM_BACTA_PICKUP", "item_bacta_canister", "INV_BACTA_CANISTER"),
    ("ITM_SEEKER_PICKUP", "item_seeker", "INV_SEEKER"),
    ("ITM_LA_GOGGLES_PICKUP", "item_lightamp_goggles", "INV_LIGHTAMP_GOGGLES"),
    ("ITM_SENTRY_GUN_PICKUP", "item_sentry", "INV_SENTRY"),
    ("ITM_GOODIE_KEY_PICKUP", "item_goodie_key", "INV_GOODIE_KEY"),
    ("ITM_SECURITY_KEY_PICKUP", "item_security_key", "INV_SECURITY_KEY"),
]

# One model for every weapon. cgame registers the weapon model the first time a
# weapon is drawn and stops with "Couldn't find weapon model" if the field is
# empty, so something has to be named; what it looks like is not what these
# lanes are about.
FIXTURE_WEAPON_MODEL = "models/players/jkx/model.glm"


def weapon_enum(repo, game):
    """The WP_ enum in source order, minus the bookends."""
    path = os.path.join(repo, "games", game, "game", "weapons.h")
    text = open(path, encoding="latin-1").read()
    start = text.index("WP_NONE")
    end = text.index("WP_NUM_WEAPONS", start)
    names = []
    for name in re.findall(r"\bWP_[A-Z0-9_]+\b", text[start:end]):
        if name != "WP_NONE" and name not in names:
            names.append(name)
    if not names:
        raise SystemExit("no WP_ enum found in %s" % path)
    return names


def item_names(repo, game):
    """Every ITM_ name g_itemLoad.cpp will accept."""
    path = os.path.join(repo, "games", game, "game", "g_itemLoad.cpp")
    text = open(path, encoding="latin-1").read()
    return set(re.findall(r'"(ITM_[A-Z0-9_]+)"', text))


def item_for(weapon):
    return NAME_EXCEPTIONS.get(weapon, "ITM_" + weapon[len("WP_"):] + "_PICKUP")


def classname_for(weapon):
    return "weapon_" + weapon[len("WP_"):].lower()


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    ap = argparse.ArgumentParser()
    ap.add_argument("--game", required=True, choices=("ja", "jo"))
    ap.add_argument("--out", required=True, help="directory to write into")
    ap.add_argument("--repo", default=os.path.abspath(os.path.join(here, "..", "..")))
    args = ap.parse_args()

    weapons = weapon_enum(args.repo, args.game)
    known = item_names(args.repo, args.game)

    covered, skipped = [], []
    for weapon in weapons:
        name = item_for(weapon)
        (covered if name in known else skipped).append((weapon, name))

    os.makedirs(args.out, exist_ok=True)

    header = (
        "// Generated by tools/verify/make_item_tables.py --game %s\n"
        "// Do not edit: the weapon list comes out of games/%s/game/weapons.h and\n"
        "// the item names out of games/%s/game/g_itemLoad.cpp, so this file is\n"
        "// whatever those two currently say. See the long note in the script.\n"
        % (args.game, args.game, args.game)
    )

    with open(os.path.join(args.out, "items.dat"), "w") as f:
        f.write(header + "\n")
        for weapon, name in covered:
            f.write(
                "{\n\titemname\t%s\n\tclassname\t\"%s\"\n"
                "\ttype\t\tIT_WEAPON\n\ttag\t\t\t%s\n}\n\n"
                % (name, classname_for(weapon), weapon)
            )
        for name, classname, tag in HOLDABLES:
            if name not in known:
                continue
            f.write(
                "{\n\titemname\t%s\n\tclassname\t\"%s\"\n"
                "\ttype\t\tIT_HOLDABLE\n\ttag\t\t\t%s\n}\n\n"
                % (name, classname, tag)
            )

    with open(os.path.join(args.out, "weapons.dat"), "w") as f:
        f.write(header + "\n")
        for weapon, _ in covered:
            f.write(
                "{\n\tweapontype\t%s\n\tweaponmodel\t\"%s\"\n}\n\n"
                % (weapon, FIXTURE_WEAPON_MODEL)
            )

    print("%s: %d weapon(s), %d holdable(s)" % (args.game, len(covered), len(HOLDABLES)))
    if skipped:
        # Named rather than silent. A weapon with no item name is one the game
        # cannot hand out at all, and if a map ever asks for one this line is
        # the first place to look.
        print("  no item name in this game, left out: %s"
              % ", ".join(w for w, _ in skipped), file=sys.stderr)


if __name__ == "__main__":
    main()
