#!/usr/bin/env python3
"""One command that measures everything the plan is betting on.

The verification checklist in docs/Phase1-Report.md needs a GPU and the retail
game files, so it cannot run in CI. This turns it into a single command with no
arguments:

    python tools/verify/verify.py

The game is found in the Steam libraries; --game overrides that when it is
installed somewhere else. It launches the engine several times with generated
configs, times each run, collects the console output, and writes
verification-report.md next to itself. Nothing is typed at the console and
nothing has to be watched.

What it measures, and why each one matters:

  startup            what a persistent pipeline cache saves. Upstream created
                     the cache with no initial data and never saved it, so up
                     to 2304 pipeline definitions were compiled from scratch on
                     every launch.
  vid_restart        the same cost again, and the one players hit most.
  map load           dominated by the IBL bake: every cubemap probe is six full
                     scene renders plus convolution. At 128 probes that is 768
                     renders, and it is the argument for caching the bake.
  lighting path      whether PBR is actually on. On a device reporting
                     maxBoundDescriptorSets < 11 it silently switched itself
                     off, so a measurement could be of the wrong path entirely.
  validation         with a debug build, how clean the renderer is.

Requires only Python 3.9+. No dependencies.
"""

from __future__ import annotations

import argparse
import json
import os
import platform
import re
import statistics
import subprocess
import sys
import time
from pathlib import Path

# --------------------------------------------------------------------------
# scenarios
# --------------------------------------------------------------------------

# Each scenario is a config the engine executes on startup. Every one ends in
# quit, so the process exits on its own and the wall clock is the measurement.
SCENARIOS = {
    "startup": {
        "label": "startup to main menu",
        "cfg": [
            "vkinfo",
            "condump jkx_startup.txt",
            "quit",
        ],
        "note": "cost a persistent pipeline cache removes",
    },
    "vid_restart": {
        "label": "startup + vid_restart",
        "cfg": [
            "vid_restart",
            "vkinfo",
            "condump jkx_vidrestart.txt",
            "quit",
        ],
        "note": "subtract startup to get the restart cost alone",
    },
    "map": {
        "label": "startup + map load",
        "cfg": [
            "map {map}",
            "wait 40",
            "condump jkx_map.txt",
            "quit",
        ],
        "note": "subtract startup to get the load cost alone",
    },
}


def build_cfg(lines: list[str], mapname: str) -> str:
    header = [
        "// Generated by tools/verify/verify.py. Safe to delete.",
        "seta com_maxfps 250",
        "seta r_fullscreen 0",
        "seta r_mode 4",
        "seta cl_renderer rd-vulkan",
        "seta s_initsound 0",   # keep audio init out of the timings
        "seta in_joystick 0",
    ]
    body = [line.replace("{map}", mapname) for line in lines]
    return "\n".join(header + body) + "\n"


# --------------------------------------------------------------------------
# console output parsing
# --------------------------------------------------------------------------

PATTERNS = {
    "lighting_path": re.compile(r"JKX: lighting path = (\w+)"),
    "max_bound_sets": re.compile(r"maxBoundDescriptorSets (\d+)"),
    "vendor": re.compile(r"VK_VENDOR:\s*(.+)"),
    "renderer": re.compile(r"VK_RENDERER:\s*(.+)"),
    "version": re.compile(r"VK_VERSION:\s*(.+)"),
    "pipeline_handles": re.compile(r"pipeline handles:\s*(\d+)"),
    "pipeline_defs": re.compile(r"pipeline descriptors:\s*(\d+)"),
    "cache_reused": re.compile(r"reusing pipeline cache \((\d+) KiB\)"),
    "cache_saved": re.compile(r"saved pipeline cache \((\d+) KiB\)"),
    "cache_rebuild": re.compile(r"pipeline cache is for a different device"),
    "cubemaps": re.compile(r"(\d+) cubemaps"),
}

VALIDATION = re.compile(r"(VUID-[A-Za-z0-9_\-]+|validation layer|Validation Error)")


def parse_console(text: str) -> dict:
    out: dict = {}
    for key, pattern in PATTERNS.items():
        match = pattern.search(text)
        if match:
            out[key] = match.group(1).strip() if match.groups() else True
    out["validation_hits"] = sorted(set(VALIDATION.findall(text)))
    return out


# --------------------------------------------------------------------------
# finding the games
# --------------------------------------------------------------------------

# Steam app ids and the directory each one installs into.
STEAM_GAMES = [
    (6020, "Jedi Academy", "Star Wars Jedi Knight - Jedi Academy", "jka"),
    (6030, "Jedi Outcast", "Star Wars Jedi Knight II - Jedi Outcast", "jk2"),
]

# Folder names Steam has used for these two over the years. Both games have been
# renamed more than once, so match on any of them rather than on one.
INSTALL_DIR_ALIASES = {
    "jka": [
        "Jedi Academy",
        "Star Wars Jedi Knight - Jedi Academy",
        "STAR WARS Jedi Knight - Jedi Academy",
        "Star Wars Jedi Knight Jedi Academy",
    ],
    "jk2": [
        "Jedi Outcast",
        "Star Wars Jedi Knight II - Jedi Outcast",
        "STAR WARS Jedi Knight II - Jedi Outcast",
        "Star Wars Jedi Knight II Jedi Outcast",
    ],
}


def steam_roots() -> list[Path]:
    """Every Steam installation this machine might have."""
    roots: list[Path] = []
    system = platform.system()

    if system == "Windows":
        try:
            import winreg  # noqa: PLC0415 - Windows only

            for hive, key in ((winreg.HKEY_CURRENT_USER, r"Software\Valve\Steam"),
                              (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\WOW6432Node\Valve\Steam")):
                try:
                    with winreg.OpenKey(hive, key) as handle:
                        for value in ("SteamPath", "InstallPath"):
                            try:
                                roots.append(Path(winreg.QueryValueEx(handle, value)[0]))
                            except OSError:
                                pass
                except OSError:
                    pass
        except ImportError:
            pass
        roots += [
            Path(r"C:\Program Files (x86)\Steam"),
            Path(r"C:\Program Files\Steam"),
        ]
    else:
        home = Path.home()
        roots += [
            home / ".steam" / "steam",
            home / ".steam" / "root",
            home / ".local" / "share" / "Steam",
            # flatpak keeps its own copy
            home / ".var" / "app" / "com.valvesoftware.Steam" / "data" / "Steam",
        ]

    seen: list[Path] = []
    for root in roots:
        try:
            resolved = root.expanduser().resolve()
        except OSError:
            continue
        if resolved.is_dir() and resolved not in seen:
            seen.append(resolved)
    return seen


# A quoted absolute path: either a drive letter followed by one or two
# backslashes, or a leading slash. Steam escapes backslashes in the file, so
# "D:\\Games" on disk is a single path with doubled separators, but not every
# writer of this file bothers, hence the optional second one.
VDF_PATH = re.compile(r'"((?:[A-Za-z]:\\\\?|/)[^"]*)"')


def vdf_paths(text: str) -> list[str]:
    """Absolute paths mentioned in a libraryfolders.vdf, unescaped.

    Valve's key-value format has changed shape twice. Rather than parse it
    properly, pull out every quoted absolute path; that survives all three
    versions, and the caller drops the ones that are not directories.
    """
    return [m.replace("\\\\", "\\") for m in VDF_PATH.findall(text)]


def steam_libraries(root: Path) -> list[Path]:
    """Every library folder, including the ones on other drives."""
    libraries = [root]

    for name in ("steamapps", "SteamApps"):
        vdf = root / name / "libraryfolders.vdf"
        if not vdf.is_file():
            continue
        try:
            text = vdf.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        for candidate in vdf_paths(text):
            path = Path(candidate)
            if path.is_dir() and path not in libraries:
                libraries.append(path)

    return libraries


# Installs seen in the wild that are worth trying before scanning anything.
# Cheap to check and skipped when absent, so an entry that is wrong for one
# machine costs nothing on another.
KNOWN_INSTALLS = [
    ("jka", r"D:\Games\Steam\steamapps\common\Jedi Academy"),
]


def game_root(install: Path) -> Path | None:
    """The directory the engine should treat as fs_basepath.

    Two layouts exist. The retail and older Steam depots put everything under
    GameData; the current Steam depot of Jedi Academy has base/ directly in the
    install folder, with JediAcademy.exe next to it. Both are valid, so pick
    whichever one actually holds base/ rather than insisting on GameData.
    """
    if (install / "GameData" / "base").is_dir():
        return install / "GameData"
    if (install / "base").is_dir():
        return install
    return None


def find_steam_games() -> list[dict]:
    """Every install we know how to drive, as a list of game roots."""
    found: list[dict] = []
    seen: set[Path] = set()
    labels = {key: label for _appid, label, _dir, key in STEAM_GAMES}
    appids = {key: appid for appid, _label, _dir, key in STEAM_GAMES}

    def add(key: str, install: Path, library: Path | None) -> None:
        root = game_root(install)
        if root is None:
            return  # present in Steam but never fully installed
        resolved = root.resolve()
        if resolved in seen:
            return
        seen.add(resolved)
        found.append({
            "key": key,
            "label": labels[key],
            "appid": appids[key],
            "path": resolved,
            "library": library,
        })

    for key, hint in KNOWN_INSTALLS:
        install = Path(hint)
        if install.is_dir():
            add(key, install, None)

    for root in steam_roots():
        for library in steam_libraries(root):
            for name in ("steamapps", "SteamApps"):
                common = library / name / "common"
                if not common.is_dir():
                    continue

                for _appid, _label, _default_dir, key in STEAM_GAMES:
                    for alias in INSTALL_DIR_ALIASES[key]:
                        install = common / alias
                        if install.is_dir():
                            add(key, install, library)
    return found


def not_found_message() -> str:
    """Says which of the two things went wrong, because the fix differs."""
    roots = steam_roots()
    if not roots:
        return ("No Steam installation found on this machine.\n"
                "Pass --game with the path to the game's install folder.")
    return ("Steam is installed, but neither Jedi Academy nor Jedi Outcast is.\n"
            "Searched: " + ", ".join(str(r) for r in roots) + "\n"
            "If the game lives elsewhere, pass --game with its install folder.")


def resolve_game(args) -> Path:
    """--game if given, otherwise whatever Steam has installed."""
    if args.game:
        path = Path(args.game).expanduser().resolve()
        if not path.is_dir():
            raise SystemExit(f"game directory not found: {path}")
        # Accept either the install folder or the GameData inside it.
        root = game_root(path)
        if root is None:
            raise SystemExit(f"no base/ directory under {path} or {path / 'GameData'}; "
                             "is this the game's install folder?")
        return root.resolve()

    games = find_steam_games()
    if not games:
        raise SystemExit(not_found_message())

    wanted = args.title
    if wanted:
        matches = [g for g in games if g["key"] == wanted]
        if not matches:
            raise SystemExit(f"{wanted} is not installed; found: "
                             + ", ".join(g["key"] for g in games))
    else:
        # Default to Jedi Academy: it is what the renderer was written against.
        matches = [g for g in games if g["key"] == "jka"] or games

    chosen = matches[0]
    print(f"found    : {chosen['label']} (app {chosen['appid']})")
    if len(games) > 1:
        others = ", ".join(f"{g['key']}" for g in games if g is not chosen)
        print(f"           also installed: {others} (use --title to switch)")
    return chosen["path"]


# --------------------------------------------------------------------------
# running
# --------------------------------------------------------------------------

# Engines that can run rd-vulkan, best first. JKX is what this tree builds;
# EternalJK is the fork the renderer came from and the only thing that can run
# it until phase 2 lands; OpenJK is here because the JKX binaries are its
# targets renamed, so an older checkout produces those names.
ENGINE_NAMES = [
    "jkx_ja.x86_64.exe", "jkx_ja.x86_64", "jkx_ja.exe",
    "jkx_jo.x86_64.exe", "jkx_jo.x86_64", "jkx_jo.exe",
    "eternaljk.x86_64.exe", "eternaljk.x86.exe", "eternaljk.x86_64",
    "openjk.x86_64.exe", "openjk.x86.exe", "openjk.x86_64",
    "openjk_sp.x86_64.exe", "openjk_sp.x86_64",
]

# The retail executables. Finding one of these means the game is where we think
# it is and only the engine is missing, which is a different message from "this
# is not a game directory at all". None of them can run the Vulkan renderer:
# they are the 2003 binaries, and rd-vulkan is loaded by name from a build of
# ours. Listing them is how the tool tells the difference.
RETAIL_NAMES = [
    "JediAcademy.exe", "jasp.exe", "jamp.exe",
    "JediOutcast.exe", "jk2sp.exe", "jk2mp.exe", "jk2gamex86.exe",
]


def find_binary(game_dir: Path, explicit: str | None) -> Path:
    if explicit:
        candidate = Path(explicit).expanduser()
        if not candidate.is_file():
            raise SystemExit(f"binary not found: {candidate}")
        return candidate

    # The engine has to sit next to base/, but a build directory in this repo is
    # worth checking too: it saves a copy for anyone measuring a fresh build.
    search = [game_dir, game_dir.parent]
    repo = Path(__file__).resolve().parents[2]
    search += [repo / "build", repo / "build" / "Release", repo / "build-san"]

    for directory in search:
        for name in ENGINE_NAMES:
            candidate = directory / name
            if candidate.is_file():
                return candidate

    retail = [name for name in RETAIL_NAMES if (game_dir / name).is_file()]
    if retail:
        raise SystemExit(
            f"{game_dir} holds the retail game ({', '.join(retail)}) but no engine of ours.\n"
            "The retail executables are the 2003 build: they cannot load rd-vulkan,\n"
            "so there is nothing here to measure.\n"
            "\n"
            "Copy the built engine into that folder, or pass --binary with its path.\n"
            f"Looked for: {', '.join(ENGINE_NAMES[:6])} ..."
        )

    raise SystemExit(
        f"no engine binary found in {game_dir}.\n"
        f"Looked for: {', '.join(ENGINE_NAMES)}\n"
        "Pass --binary to point at it explicitly."
    )


def home_path(game_dir: Path) -> Path:
    """Where the engine writes condumps, unless it is a portable build."""
    system = platform.system()
    if system == "Windows":
        base = Path(os.environ.get("USERPROFILE", "~")).expanduser() / "Documents"
        for name in ("EternalJK", "OpenJK", "JKX"):
            candidate = base / name / "base"
            if candidate.is_dir():
                return candidate
        return base / "EternalJK" / "base"
    base = Path.home() / ".local" / "share"
    for name in ("EternalJK", "OpenJK", "JKX"):
        candidate = base / name / "base"
        if candidate.is_dir():
            return candidate
    return base / "EternalJK" / "base"


def run_scenario(binary: Path, game_dir: Path, cfg_dir: Path, name: str, mapname: str,
                 timeout: int) -> tuple[float, int]:
    scenario = SCENARIOS[name]
    cfg_name = f"jkx_verify_{name}.cfg"
    (cfg_dir / cfg_name).write_text(build_cfg(scenario["cfg"], mapname), encoding="ascii")

    cmd = [
        str(binary),
        "+set", "fs_basepath", str(game_dir),
        "+set", "fs_game", "",
        "+exec", cfg_name,
    ]

    start = time.perf_counter()
    try:
        proc = subprocess.run(cmd, cwd=str(game_dir), capture_output=True, timeout=timeout)
        code = proc.returncode
    except subprocess.TimeoutExpired:
        return (float(timeout), -1)
    return (time.perf_counter() - start, code)


def read_dump(home: Path, name: str) -> str:
    path = home / name
    if not path.is_file():
        return ""
    return path.read_text(encoding="utf-8", errors="replace")


# --------------------------------------------------------------------------
# report
# --------------------------------------------------------------------------

def fmt(seconds: float | None) -> str:
    return "-" if seconds is None else f"{seconds:.1f} s"


def write_report(path: Path, results: dict, info: dict, args) -> None:
    startup = results.get("startup", {}).get("median")
    restart = results.get("vid_restart", {}).get("median")
    mapload = results.get("map", {}).get("median")

    restart_only = (restart - startup) if (restart and startup) else None
    map_only = (mapload - startup) if (mapload and startup) else None

    lines = [
        "# JKX: verification run",
        "",
        f"- date: {time.strftime('%Y-%m-%d %H:%M')}",
        f"- host: {platform.system()} {platform.machine()}",
        f"- binary: `{args.binary or 'auto-detected'}`",
        f"- game: `{args.resolved_game}`",
        f"- map: `{args.map}`",
        f"- runs per scenario: {args.runs}",
        "",
        "## Device",
        "",
    ]
    for key, label in (("vendor", "vendor"), ("renderer", "renderer"), ("version", "Vulkan")):
        lines.append(f"- {label}: {info.get(key, '?')}")

    path_name = info.get("lighting_path")
    sets = info.get("max_bound_sets")
    lines += ["", "## Lighting path", ""]
    if path_name is None:
        lines.append("Not reported. This build predates the diagnostic; rebuild the renderer from")
        lines.append("this tree, or treat every number below as being of an unknown path.")
    elif path_name == "PBR":
        lines.append(f"**PBR is active** (maxBoundDescriptorSets {sets}). Measurements below are of the PBR path.")
    else:
        lines.append(f"**PBR is OFF, fastlight is running** (maxBoundDescriptorSets {sets}).")
        lines.append("")
        lines.append("Everything below therefore measures the non-PBR path. If this device reports")
        lines.append("fewer than 11 descriptor sets, that is the limit bindless removes; it is why")
        lines.append("bindless is on the critical path rather than an optimisation.")

    lines += [
        "",
        "## Timings",
        "",
        "| what | median | note |",
        "|---|---|---|",
        f"| startup to main menu | {fmt(startup)} | cost a persistent pipeline cache removes |",
        f"| vid_restart alone | {fmt(restart_only)} | the same cost, and the one players hit |",
        f"| map load alone | {fmt(map_only)} | dominated by the IBL bake |",
        "",
    ]

    for name, data in results.items():
        if data.get("samples"):
            spread = ", ".join(f"{s:.1f}" for s in data["samples"])
            lines.append(f"- {SCENARIOS[name]['label']}: {spread} s")
    lines.append("")

    lines += ["## Pipeline cache", ""]
    if info.get("cache_reused"):
        lines.append(f"Reused a cache of {info['cache_reused']} KiB, so this build has the persistent cache.")
    elif info.get("cache_saved"):
        lines.append(f"Saved {info['cache_saved']} KiB. Run again: the second startup should be faster.")
    elif info.get("cache_rebuild"):
        lines.append("Cache was rejected as belonging to another device or driver, and rebuilt.")
    else:
        lines.append("No cache messages. Either this build predates the persistent cache, or the")
        lines.append("homepath is not writable. The startup number above is then the uncached cost.")

    lines += ["", "## Pipelines", ""]
    lines.append(f"- definitions: {info.get('pipeline_defs', '?')}")
    lines.append(f"- created objects: {info.get('pipeline_handles', '?')}")
    lines.append("")
    lines.append("Dynamic rendering plus extended dynamic state should cut the object count by")
    lines.append("roughly an order of magnitude; this is the before number.")

    hits = info.get("validation_hits") or []
    lines += ["", "## Validation", ""]
    if hits:
        lines.append(f"{len(hits)} distinct message(s):")
        lines.append("")
        for h in hits[:20]:
            lines.append(f"- `{h}`")
    else:
        lines.append("None seen. Note that validation layers are only active in a debug build,")
        lines.append("so silence here is not proof of cleanliness.")

    lines += [
        "",
        "## Still needs a human",
        "",
        "- FPS against rd-vanilla on the same scene (`/cl_renderer rd-vanilla; vid_restart`)",
        "- one RenderDoc capture: draw call count, pipeline switches, where time goes",
        "- hitching when new materials first appear, which is the lazy pipeline creation",
        "",
        "Attach this file and the console dumps from the homepath.",
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--game", default=None,
                        help="path to GameData (auto-detected from Steam when omitted)")
    parser.add_argument("--title", choices=["jka", "jk2"], default=None,
                        help="which game, when both are installed (default: jka)")
    parser.add_argument("--list", action="store_true", help="list detected installs and exit")
    parser.add_argument("--binary", default=None, help="engine binary (auto-detected by default)")
    parser.add_argument("--map", default="mp/ffa3", help="map to load")
    parser.add_argument("--runs", type=int, default=3, help="runs per scenario (median is reported)")
    parser.add_argument("--timeout", type=int, default=300, help="seconds before a run is abandoned")
    parser.add_argument("--out", default=None, help="report path")
    args = parser.parse_args(argv[1:])

    if args.list:
        games = find_steam_games()
        if not games:
            print(not_found_message())
            return 1
        for g in games:
            print(f"{g['key']:4s}  {g['label']:16s}  {g['path']}")
        return 0

    game_dir = resolve_game(args)
    args.resolved_game = game_dir

    binary = find_binary(game_dir, args.binary)
    cfg_dir = game_dir / "base"
    if not cfg_dir.is_dir():
        raise SystemExit(f"no base/ directory under {game_dir}")

    home = home_path(game_dir)
    print(f"binary   : {binary}")
    print(f"game     : {game_dir}")
    print(f"homepath : {home}")
    print(f"map      : {args.map}")
    print()

    # Old dumps would otherwise be parsed as if they were from this run.
    for stale in ("jkx_startup.txt", "jkx_vidrestart.txt", "jkx_map.txt"):
        target = home / stale
        if target.is_file():
            target.unlink()

    results: dict = {}
    for name, scenario in SCENARIOS.items():
        samples = []
        print(f"{scenario['label']}: ", end="", flush=True)
        for run in range(args.runs):
            elapsed, code = run_scenario(binary, game_dir, cfg_dir, name, args.map, args.timeout)
            if code == -1:
                print(f"\n  run {run + 1} timed out after {args.timeout}s; skipping this scenario")
                samples = []
                break
            samples.append(elapsed)
            print(f"{elapsed:.1f}s ", end="", flush=True)
        print()
        if samples:
            results[name] = {"samples": samples, "median": statistics.median(samples)}

    console = "\n".join(
        read_dump(home, name) for name in ("jkx_startup.txt", "jkx_vidrestart.txt", "jkx_map.txt")
    )
    if not console.strip():
        print("\nWarning: no console dumps found in the homepath. Timings are still valid,")
        print("but the device, lighting path and validation sections will be empty.")
    info = parse_console(console)

    out = Path(args.out) if args.out else Path(__file__).resolve().parent / "verification-report.md"
    write_report(out, results, info, args)

    print()
    print(f"report: {out}")
    if info.get("lighting_path") == "fastlight":
        print("NOTE: PBR was OFF for this run; see the report.")
    if info.get("validation_hits"):
        print(f"NOTE: {len(info['validation_hits'])} validation message(s); see the report.")

    (out.with_suffix(".json")).write_text(
        json.dumps({"results": results, "info": info}, indent=2, default=str), encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
