#============================================================================
# assets/fonts -> base/fonts
#
# The atlases are generated, but they are generated by hand and checked in, not
# built here. Building them would put freetype, pillow and numpy between someone
# and a working game for the sake of four files that change when a typeface
# changes, which is roughly never. tools/fontgen/build_fonts.py regenerates
# them; CI runs it with --check so they cannot drift from the tool that made
# them.
#
# So this is a copy. It is here rather than in a pak because loose files in
# base/ are what the engine reads anyway, and because a font you can open in an
# image viewer while debugging text is worth more than a few kilobytes saved.
#============================================================================

function(jkx_add_fonts TARGET_NAME)
    set(FONT_SRC "${CMAKE_SOURCE_DIR}/assets/fonts")
    set(FONT_DST "${JKX_GAME_DATA_DIR}/fonts")

    file(GLOB FONT_FILES "${FONT_SRC}/*.jkxfont" "${FONT_SRC}/*.png")

    if(NOT FONT_FILES)
        message(WARNING
            "assets/fonts is empty. Run tools/fontgen/build_fonts.py, or the game "
            "will start with no text in it.")
        return()
    endif()

    set(COPIED "")
    foreach(SRC ${FONT_FILES})
        get_filename_component(NAME "${SRC}" NAME)
        set(DST "${FONT_DST}/${NAME}")
        add_custom_command(
            OUTPUT "${DST}"
            COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${SRC}" "${DST}"
            DEPENDS "${SRC}"
            COMMENT "font ${NAME}"
            VERBATIM)
        list(APPEND COPIED "${DST}")
    endforeach()

    add_custom_target(${TARGET_NAME} ALL DEPENDS ${COPIED})

    list(LENGTH FONT_FILES FONT_COUNT)
    message(STATUS "Fonts: ${FONT_COUNT} file(s) from assets/fonts")
endfunction()
